Index: git/Makefile
===================================================================
--- git.orig/Makefile
+++ git/Makefile
@@ -62,8 +62,8 @@ $(OBJ): %.o: %.c $(HDRS)
 
 # Build the manual page
 
-fscryptctl.1: fscryptctl.1.md
-	pandoc -s -t man $+ > $@
+#fscryptctl.1: fscryptctl.1.md
+#	pandoc -s -t man $+ > $@
 
 ##############################################################################
 
@@ -133,7 +133,7 @@ test-all:
 
 # Installation, uninstallation, and cleanup targets
 
-all:fscryptctl fscryptctl.1
+all:fscryptctl #fscryptctl.1
 
 .PHONY: all install install-bin install-man uninstall clean
 
@@ -141,15 +141,15 @@ install-bin: fscryptctl
 	install -d $(DESTDIR)$(BINDIR)
 	install -m755 $< $(DESTDIR)$(BINDIR)
 
-install-man: fscryptctl.1
-	install -d $(DESTDIR)$(MANDIR)/man1
-	install -m644 $< $(DESTDIR)$(MANDIR)/man1
+#install-man: fscryptctl.1
+#	install -d $(DESTDIR)$(MANDIR)/man1
+#	install -m644 $< $(DESTDIR)$(MANDIR)/man1
 
 install:install-bin install-man
 
 uninstall:
 	rm -f $(DESTDIR)$(BINDIR)/fscryptctl
-	rm -f $(DESTDIR)$(MANDIR)/man1/fscryptctl.1
+#	rm -f $(DESTDIR)$(MANDIR)/man1/fscryptctl.1
 
 clean:
 	rm -f fscryptctl fscryptctl.1 *.o *.pyc
